app_InterfaceLanguage=chi
app_PreferredLanguage=chi
app_DataDir=/opt/makemkv
app_DestinationDir=/output
app_DestinationType=3
app_ExpertMode=1
app_ShowAVSyncMessages=1
app_UpdateEnable=0
app_Key=__MAKE_MKV_BETA_KEY__
